### ISSUE TITLE
Unable to use mopidy-touchscreen

### ISSUE THREAD

**Issue by Trecoolius** [9and3r/mopidy-touchscreen#17]
Been scratching my head for two days and ca't get rid of this:

`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mopidy_touchscreen/screen_manager.py", line 69, in init_manager
    self.base_size, self, self.fonts),
  File "/usr/local/lib/python2.7/dist-packages/mopidy_touchscreen/screens/playlist_screen.py", line 18, in __init__
    self.playlists_loaded()
  File "/usr/local/lib/python2.7/dist-packages/mopidy_touchscreen/screens/playlist_screen.py", line 34, in playlists_loaded
    self.list_view.set_list(self.playlists_strings)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_touchscreen/graphic_utils/list_view.py", line 49, in set_list
    self.load_new_item_position(0)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_touchscreen/graphic_utils/list_view.py", line 69, in load_new_item_position
    self.pos[1] + self.base_size * z), (width, -1))
  File "/usr/local/lib/python2.7/dist-packages/mopidy_touchscreen/graphic_utils/screen_objects.py", line 234, in __init__
    background=background, scroll_no_fit=scroll_no_fit)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_touchscreen/graphic_utils/screen_objects.py", line 95, in __init__
    self.box = self.font.render(text, True, self.color)
UnicodeError: A Unicode character above '\uFFFF' was found; not supported
ERROR    Got un-handled exception from TouchScreen
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/commands.py", line 237, in _actor_error_handling
    yield
  File "/usr/lib/python2.7/dist-packages/mopidy/commands.py", line 411, in start_frontends
    frontend_class.start(config=config, core=core)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 94, in start
    obj = cls(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_touchscreen/touch_screen.py", line 50, in __init__
    self.resolution_factor)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_touchscreen/screen_manager.py", line 48, in __init__
    self.init_manager(size)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_touchscreen/screen_manager.py", line 128, in init_manager
    self.options_changed()
  File "/usr/local/lib/python2.7/dist-packages/mopidy_touchscreen/screen_manager.py", line 231, in options_changed
    self.screens[menu_index].options_changed()
TypeError: 'NoneType' object has no attribute '__getitem__'
`

it launches mopidy afterwards, but it's just a black window. Tried setting the user to root in /lib/systemd/system/mopidy.service  and the daemon to root in /etc/init.d/mopidy to no avail. I also changed the env var to sdl_audiodriver = none and still can't use it. Any help would be much appreciated.

**Comment by vrs01** [comment]
I had the same problem, but when I started mopidy as non-root it worked! I couldn't find out yet what makes the difference. I have the same config values for root and non-root.

**Comment by vrs01** [comment]
Mopidy-touchscreen only works for me when I disable mopidy-spotify. With mopidy-spotify enabled I get the same error message as in the first post.

**Comment by vrs01** [comment]
Mopidy-touchscreen has problems with displaying spotify playlists with weird characters in their names. I deleted one playlist with some symbols in the name and then it worked.

**Comment by Trecoolius** [comment]
That did the trick, thanks a lot!
