### ISSUE TITLE
Error when playing internet radio / streaming audio

### ISSUE THREAD

**Issue by john-a-harris** [9and3r/mopidy-touchscreen#21]
An error is being thrown when I play an internet radio station via the tunein plugin or a url. I think it's because there's no track length for the stream.

`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mopidy_touchscreen/touch_screen.py", line 106, in track_playback_started
    self.screen_manager.track_started(tl_track)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_touchscreen/screen_manager.py", line 178, in track_started
    self.screens[main_screen_index].track_started(track.track)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_touchscreen/screens/main_screen.py", line 120, in track_started
    track.length / 1000))
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'`

**Comment by 9and3r** [comment]
Thanks for the info. This should be fixed in the development version.
